apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab-registry
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lab-registry
  template:
    metadata:
      labels:
        app: lab-registry
    spec:
      containers:
      - name: registry
        image: registry:2
        ports:
        - containerPort: 5000
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 50m
            memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: lab-registry
  namespace: kube-system
spec:
  selector:
    app: lab-registry
  ports:
  - port: 5000
    targetPort: 5000
