apiVersion: v1
kind: Pod
metadata:
  name: test-signed-api
  namespace: demo
spec:
  containers:
  - name: api
    image: lab-registry.kube-system.svc.cluster.local:5000/w10-secu-api:0.0.2
    resources:
      limits:
        cpu: 200m
        memory: 128Mi
