apiVersion: v1
kind: Pod
metadata:
  name: test-unsigned-ghcr
  namespace: demo
spec:
  containers:
  - name: api
    image: ghcr.io/tuu-ngo/w10-secu-api:0.0.1
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
