apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: db-creds
  namespace: demo
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  refreshInterval: 30s
  secretStoreRef:
    name: fake-store
    kind: SecretStore
  target:
    name: db-secret
    creationPolicy: Owner
  data:
  - secretKey: password
    remoteRef:
      key: demo/db/password