apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: fake-store
  namespace: demo
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  provider:
    fake:
      data:
      - key: demo/db/password
        value: password-v1